### PR TITLE
Added a couple props, updated event emitter

### PR DESCRIPTION
**Pull request by Machine-Maker**
I changed the callback function to use vue event system. And added a couple new props explained in the readme. Also added dynamic changing of the title to the filename(s) selected.

### CODE REVIEW

**Comment by DoritoBandito** [comment]
I think even if `noTitleUpdate` is false, it should still show the `title` prop as the button text if there is no `uTitle` and `uTitle` should only be shown as button text once a file has been selected and `noTitleUpdate` is false.

**Comment by Machine-Maker** [comment]
Yeah that’s a good idea. I’ll adjust accordingly.

**Comment by Machine-Maker** [comment]
mmkay, should be changed now

**Comment by DoritoBandito** [comment]
Looks good, thanks for your contribution.

**Review by DoritoBandito — APPROVED** [review]

**Pull request merged**
